name: Staging Deployment & E2E Testing

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_run:
    workflows: ['Continuous Integration']
    types:
      - completed

jobs:
  build-and-push-images:
    name: Build & Push Docker Images to GitHub Container Registry
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'push' || github.event_name == 'pull_request' ||
      (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Create .env File from Secrets
        run: |
          echo "VITE_BACKEND_HOST=${{ secrets.BACKEND_HOST }}" >> .env
          echo "VITE_BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
          echo "FRONTEND_PORT=3000" >> .env

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Images Using Docker Compose
        run: |
          docker-compose build \
            --build-arg VITE_BACKEND_HOST=${{ secrets.BACKEND_HOST }} \
            --build-arg VITE_BACKEND_PORT=${{ secrets.BACKEND_PORT }}

          docker tag ev-fleet-telemetry-dashboard_backend ghcr.io/${{ github.repository_owner }}/backend-staging:latest
          docker tag ev-fleet-telemetry-dashboard_frontend ghcr.io/${{ github.repository_owner }}/frontend-staging:latest

          docker push ghcr.io/${{ github.repository_owner }}/backend-staging:latest
          docker push ghcr.io/${{ github.repository_owner }}/frontend-staging:latest

  deploy-staging:
    name: Deploy Staging to Render
    runs-on: ubuntu-latest
    needs: build-and-push-images
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Backend to Render
        run: |
          curl -X POST "$RENDER_BACKEND_DEPLOY_HOOK"
        env:
          RENDER_BACKEND_DEPLOY_HOOK: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

      - name: Deploy Frontend to Render
        run: |
          curl -X POST "$RENDER_FRONTEND_DEPLOY_HOOK"
        env:
          RENDER_FRONTEND_DEPLOY_HOOK: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}

  e2e-tests:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Create .env File for E2E Tests
        run: |
          echo "VITE_BACKEND_HOST=${{ secrets.BACKEND_HOST }}" >> .env
          echo "VITE_BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
          echo "FRONTEND_HOST=${{ secrets.FRONTEND_HOST }}" >> .env
          echo "FRONTEND_PORT=80" >> .env

      - name: Build E2E Test Image
        run: |
          docker-compose build e2e
          docker tag ev-fleet-telemetry-dashboard_e2e e2e-tests

      - name: Run Playwright E2E Tests
        run: |
          docker run --rm \
            -e VITE_BACKEND_HOST=${{ secrets.BACKEND_HOST }} \
            -e VITE_BACKEND_PORT=${{ secrets.BACKEND_PORT }} \
            -e FRONTEND_HOST=${{ secrets.FRONTEND_HOST }} \
            -e FRONTEND_PORT=80 \
            -e TEST_HOST=${{ secrets.STAGING_URL }} \
            e2e-tests

  deploy-storybook:
    name: Deploy Storybook to GitHub Pages
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: |
          cd frontend
          pnpm install

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Clear the `gh-pages` branch before pushing Storybook (prevents overwrites)
      - name: Clear gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          cd gh-pages
          rm -rf *
          git add .
          git commit -m "Clear gh-pages"
          git push origin gh-pages

      - name: Build Storybook
        run: |
          cd frontend
          pnpm build-storybook

      - name: Deploy Storybook to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages -d frontend/storybook-static --dest storybook -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
